name: publish ShadyNagy.DapperManager to nuget
on:
  workflow_dispatch:
  push:
    branches:
      - main # Your default release branch
    paths:
      - 'src/ShadyNagy.DapperManager/**'
jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      # Required for a specific dotnet version that doesn't come with ubuntu-latest / windows-latest
      # Visit bit.ly/2synnZl to see the list of SDKs that are pre-installed with ubuntu-latest / windows-latest
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.202

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      # Publish
      - name: publish ShadyNagy.DapperManager on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/ShadyNagy.DapperManager/ShadyNagy.DapperManager.csproj # Relative to repository root
          # VERSION_FILE_PATH: Directory.Build.props # Filepath with version info, relative to repository root. Defaults to project file
          VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          TAG_COMMIT: true # Flag to enable / disable git tagging
          TAG_FORMAT: v* # Format of the git tag, [*] gets replaced with version
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key

      - name: publish ShadyNagy.DapperInMemory on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/ShadyNagy.DapperInMemory/ShadyNagy.DapperInMemory.csproj # Relative to repository root
          # VERSION_FILE_PATH: Directory.Build.props # Filepath with version info, relative to repository root. Defaults to project file
          VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          TAG_COMMIT: true # Flag to enable / disable git tagging
          TAG_FORMAT: v* # Format of the git tag, [*] gets replaced with version
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key